lank_issues_enabled: true
contact_links:
  - name: Support & Discussions
    url: https://github.com/HenrikBengtsson/future/discussions/
    about: Got a question? Something is not working? Want to share an idea?
